### ISSUE TITLE
Support postgresql 16

### ISSUE THREAD

**Issue by elysabethpc** [alitrack/duckdb_fdw#24]
Hello, please do you plan to support also postgresql 16?

I'm using duckdb_fdw in postgresql 15.5 (with 0.9.2 duckdb version) and work like a charm for my pipeline. I would like to upgrade to postgresql 16.1.

I tried to build for postgresql 16, but seem there too many changes in the  permission area in postgresql 16
https://github.com/postgres/postgres/commit/a61b1f74
https://www.postgresql.org/message-id/CA+HiwqGjJDmUhDSfv-U2qhKJjt9ST7Xh9JXC_irsAQ1TAUsJYg@mail.gmail.com

I got this error:

```
duckdb_fdw.c: In function ‘sqliteGetForeignRelSize’:
duckdb_fdw.c:552:53: error: ‘RangeTblEntry’ has no member named ‘checkAsUser’
  552 |                 Oid                     userid = rte->checkAsUser ? rte->checkAsUser : GetUserId();
      |                                                     ^~
duckdb_fdw.c:552:72: error: ‘RangeTblEntry’ has no member named ‘checkAsUser’
  552 |                 Oid                     userid = rte->checkAsUser ? rte->checkAsUser : GetUserId();
      |                                                                        ^~
duckdb_fdw.c: In function ‘sqlitePlanForeignModify’:
duckdb_fdw.c:1829:39: error: ‘RangeTblEntry’ has no member named ‘updatedCols’
 1829 |                 tmpset = bms_union(rte->updatedCols, rte->extraUpdatedCols);
      |                                       ^~
duckdb_fdw.c:1829:57: error: ‘RangeTblEntry’ has no member named ‘extraUpdatedCols’
 1829 |                 tmpset = bms_union(rte->updatedCols, rte->extraUpdatedCols);
      |                                                         ^~

```

Thank you for make this postgresql extension

**Comment by ahuarte47** [comment]
Hi @elysabethpc this [PR](https://github.com/alitrack/duckdb_fdw/pull/22) was merged, it is adding support for pg16, please, can you check?

**Comment by elysabethpc** [comment]
Thank you very much @ahuarte47 and @alitrac. Its working OK in postgresql 16.1 in fedora 38 x86_64, with duckdb 0.9.2. I didn't test it fully, but all the tests that I run by now work like a charm.
